spring.application.name=gentech_fintech
spring.datasource.url=jdbc:postgresql://localhost:5432/gentech_accounts
spring.datasource.username=postgres
spring.datasource.password=${DB_PWD}
spring.jpa.hibernate.ddl-auto=create
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/create.sql
