create table users (
                       deleted boolean not null default false,
                       flagged boolean not null default false,
                       created_at TIMESTAMP WITH TIME ZONE,
                       updated_at TIMESTAMP WITH TIME ZONE,
                       user_id bigint generated by default as identity,
                       email varchar(255),
                       name varchar(255) not null,
                       password varchar(255) not null,
                       phone varchar(255),
                       role varchar(255) default 'user',
                       primary key (user_id)
);

create table wallets (
                         balance numeric(29,2) not null default 0.00,
                         created_at TIMESTAMP WITH TIME ZONE not null,
                         wallet_id bigint generated by default as identity,
                         wallet_user bigint not null unique,
                         primary key (wallet_id)
);

create index IDX6dotkott2kjsp8vw4d0m25fb7 on users (email);
create index IDXdu5v5sr43g5bfnji4vb8hg5s3 on users (phone);
create index IDX8xsqgty5i1ch1r149wo2cj6i3 on wallets (wallet_user);

alter table if exists wallets
    add constraint FK2o8uv29yhdw7lwln49gn7h9bp
    foreign key (wallet_user) references users;