create table audit_logs (
                            id bigint generated by default as identity,
                            action varchar(255) not null,
                            initiated_at TIMESTAMP WITH TIME ZONE not null,
                            logs_user bigint,
                            primary key (id)
);

alter table if exists audit_logs
    add constraint FKaudit_logs_user
    foreign key (logs_user) references users;