create table kycs (
                      id bigint generated by default as identity,
                      url varchar(255),
                      kyc_type varchar(255),
                      status varchar(255) default 'Pending',
                      submitted_at TIMESTAMP WITH TIME ZONE,
                      reviewed_at TIMESTAMP WITH TIME ZONE,
                      kyc_user bigint,
                      primary key (id),
                      unique (kyc_user, kyc_type)
);

alter table if exists kycs
    add constraint FKkyc_user
    foreign key (kyc_user) references users;