create table two_factors (
                             id bigint generated by default as identity,
                             code varchar(255),
                             revoked boolean not null default false,
                             created_at TIMESTAMP WITH TIME ZONE,
                             expires_at TIMESTAMP WITH TIME ZONE,
                             updated_at TIMESTAMP WITH TIME ZONE,
                             two_factor_user bigint unique,
                             primary key (id)
);

alter table if exists two_factors
    add constraint FKtwo_factor_user
    foreign key (two_factor_user) references users;

create table refresh_tokens (
                                id bigint generated by default as identity,
                                token varchar(255),
                                created_at TIMESTAMP WITH TIME ZONE,
                                expires_at TIMESTAMP WITH TIME ZONE,
                                is_revoked boolean not null default false,
                                refresh_user bigint,
                                primary key (id)
);

alter table if exists refresh_tokens
    add constraint FKrefresh_user
    foreign key (refresh_user) references users;