create table two_factors (
                             id bigint generated by default as identity,
                             code varchar(255),
                             revoked boolean not null default false,
                             created_at TIMESTAMP WITH TIME ZONE,
                             expires_at TIMESTAMP WITH TIME ZONE,
                             updated_at TIMESTAMP WITH TIME ZONE,
                             two_factor_user bigint unique,
                             primary key (id)
);

alter table if exists two_factors
    add constraint FKtwo_factor_user
    foreign key (two_factor_user) references users;