create table transactions (
                              id bigint generated by default as identity,
                              description varchar(255) not null,
                              amount numeric(7, 2) not null,
                              trans_type varchar(255),
                              created_at TIMESTAMP WITH TIME ZONE,
                              sender_wallet bigint,
                              receiver_wallet bigint,
                              primary key (id)
);

alter table if exists transactions
    add constraint FKsender_wallet
    foreign key (sender_wallet) references wallets;

alter table if exists transactions
    add constraint FKreceiver_wallet
    foreign key (receiver_wallet) references wallets;